In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('bls_occupation_allocc.csv')

In [10]:
df.columns = df.iloc[0]
df = df[1:]
df = df.reset_index(drop=True)

In [11]:
df

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content
0,"Total, all occupations",00-0000,Summary,"167,849.8","174,589.0",100.0,100.0,"6,739.2",4.0,5.8,"19,174.8","48,060",—,—,—,—
1,Management occupations,11-0000,Summary,"13,181.3","14,140.9",7.9,8.1,959.6,7.3,15.1,"1,160.0","116,880",—,—,—,—
2,Top executives,11-1000,Summary,"3,977.7","4,206.7",2.4,2.4,229.0,5.8,2.7,346.5,"103,460",—,—,—,—
3,Chief executives,11-1011,Line item,313.9,331.1,0.2,0.2,17.2,5.5,28.1,23.0,"206,680",Bachelor's degree,5 years or more,NaN,OOH Content
4,General and operations managers,11-1021,Line item,"3,630.1","3,840.5",2.2,2.2,210.4,5.8,0.5,320.8,"101,280",Bachelor's degree,5 years or more,NaN,OOH Content
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,"40,310",No formal educational credential,NaN,Short-term on-the-job training,—
1113,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,[1] Data are from the Occupational Employment ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,Note: Data is unavailable for values denoted w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,"Source: Employment Projections program, U.S. B...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_majorocc = pd.read_csv('bls_occupation_majoroccgroup.csv')

In [17]:
df_majorocc.columns = df_majorocc.iloc[0]
df_majorocc = df_majorocc[1:24] # removes header and footnote rows
df_majorocc = df_majorocc.reset_index(drop=True)

In [18]:
df_majorocc

,2023 National Employment Matrix title,2023 National Employment Matrix code,"Employment, 2023","Employment, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Median annual wage, dollars, 2023[1]"
0,"Total, all occupations",00-0000,"167,849.8","174,589.0","6,739.2",4.0,"48,060"
1,Management occupations,11-0000,"13,181.3","14,140.9",959.6,7.3,"116,880"
2,Business and financial operations occupations,13-0000,"10,977.2","11,738.5",761.3,6.9,"79,050"
3,Computer and mathematical occupations,15-0000,"5,417.6","6,116.7",699.0,12.9,"104,200"
4,Architecture and engineering occupations,17-0000,"2,639.7","2,819.7",180.0,6.8,"91,420"
5,"Life, physical, and social science occupations",19-0000,"1,574.1","1,691.7",117.6,7.5,"78,280"
6,Community and social service occupations,21-0000,"3,044.7","3,291.7",247.0,8.1,"52,000"
7,Legal occupations,23-0000,"1,394.4","1,446.2",51.8,3.7,"99,220"
8,Educational instruction and library occupations,25-0000,"9,579.9","9,731.2",151.3,1.6,"59,940"
9,"Arts, design, entertainment, sports, and med...",27-0000,"3,073.1","3,203.2",130.1,4.2,"58,920"
10,Healthcare practitioners and technical occup...,29-0000,"9,781.6","10,623.3",841.7,8.6,"80,820"
11,Healthcare support occupations,31-0000,"7,516.9","8,659.3","1,142.4",15.2,"36,140"
12,Protective service occupations,33-0000,"3,630.7","3,704.7",74.0,2.0,"47,760"
13,Food preparation and serving related occupat...,35-0000,"13,580.3","14,167.2",586.8,4.3,"32,240"
14,Building and grounds cleaning and maintenanc...,37-0000,"5,640.5","5,817.4",176.9,3.1,"35,990"
15,Personal care and service occupations,39-0000,"4,346.2","4,622.3",276.1,6.4,"34,260"
16,Sales and related occupations,41-0000,"14,609.5","14,319.5",-290.0,-2.0,"36,760"
17,Office and administrative support occupations,43-0000,"19,671.9","18,975.6",-696.3,-3.5,"44,480"
18,"Farming, fishing, and forestry occupations",45-0000,982.9,964.5,-18.4,-1.9,"35,520"
19,Construction and extraction occupations,47-0000,"7,338.3","7,752.3",414.0,5.6,"55,680"
20,"Installation, maintenance, and repair occupa...",49-0000,"6,460.3","6,803.5",343.3,5.3,"53,920"
21,Production occupations,51-0000,"9,093.6","8,999.5",-94.1,-1.0,"43,630"
22,Transportation and material moving occupations,53-0000,"14,315.1","15,000.1",685.1,4.8,"40,050"

In [19]:
df_allocc = df[df['Occupation type'] == 'Line item']

In [20]:
df_allocc

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content
3,Chief executives,11-1011,Line item,313.9,331.1,0.2,0.2,17.2,5.5,28.1,23.0,"206,680",Bachelor's degree,5 years or more,NaN,OOH Content
4,General and operations managers,11-1021,Line item,"3,630.1","3,840.5",2.2,2.2,210.4,5.8,0.5,320.8,"101,280",Bachelor's degree,5 years or more,NaN,OOH Content
5,Legislators,11-1031,Line item,33.7,35.0,0.0,0.0,1.4,4.1,—,2.7,"47,290",Bachelor's degree,Less than 5 years,NaN,—
7,Advertising and promotions managers,11-2011,Line item,22.2,21.7,0.0,0.0,-0.6,-2.6,6.2,1.8,"131,870",Bachelor's degree,Less than 5 years,NaN,OOH Content
9,Marketing managers,11-2021,Line item,389.1,420.8,0.2,0.2,31.7,8.2,3.2,34.8,"157,620",Bachelor's degree,5 years or more,NaN,OOH Content
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1108,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,12.3,0.0,0.0,0.6,5.0,—,1.3,"54,690",High school diploma or equivalent,NaN,Moderate-term on-the-job training,—
1109,Wellhead pumpers,53-7073,Line item,19.4,19.0,0.0,0.0,-0.4,-2.0,—,2.0,"71,830",High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training,—
1110,Refuse and recyclable material collectors,53-7081,Line item,148.4,151.9,0.1,0.1,3.5,2.3,4.2,18.0,"45,760",No formal educational credential,NaN,Short-term on-the-job training,OOH Content
1111,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,13.2,0.0,0.0,0.5,3.9,7.2,1.4,"58,620",No formal educational credential,NaN,Short-term on-the-job training,—
1112,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,"40,310",No formal educational credential,NaN,Short-term on-the-job training,—

In [ ]:
# create a column with the major occupation group and match based on the first 2 digits of the SOC code