In [1]:
import pandas as pd

In [8]:
onet = pd.read_json("career_data_0302.json")

In [9]:
onet = onet.T
onet = onet.reset_index()

In [11]:
onet = onet.rename(columns={"index": "occupational_code"})

In [27]:
onet

,occupational_code,job_title,job_description,skills,education,work_experience,on_job_training,work_activities,alternate_titles,tools_used,technical_skills,core_tasks,supplemental_tasks
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...,"[{'Soft Skills': 'Reading Comprehension', 'Imp...",[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Aeronautics Commission Director, Agency Owner...","[Desktop calculator, Desktop computers, Notebo...","[Adobe Acrobat, AdSense Tracker, Atlassian JIR...",[Direct or coordinate an organization's financ...,"[Nominate citizens to boards or commissions., ..."
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh...","[{'Soft Skills': 'Writing', 'Importance': 4.12...",[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...",[Chief Environmental Commitment Officer (CECO)...,"[Desktop calculator, Scanners, Desktop compute...","[Adobe Acrobat, Adobe Photoshop, Email softwar...",[Monitor and evaluate effectiveness of sustain...,[]
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ...",[],[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Area Manager, Business Coordinator, Business ...","[Desktop calculator, Mobile phones, Scanners, ...","[Act!, ActionWare, Adobe Acrobat, Adobe Creati...","[Review financial statements, sales or activit...",[Manage the movement of goods into and out of ...
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes...",[],[],[],[],[],"[Alderman, Assembly Member, Assembly Person, A...","[Laser printers, Notebook computers, Tablet co...","[Adobe Acrobat, Adobe FrameMaker, Antenna Hous...",[],[]
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici...","[{'Soft Skills': 'Active Listening', 'Importan...",[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Account Director, Account Executive, Account ...","[Scanners, Desktop computers, Portable data in...","[Actuate BIRT, Adobe Acrobat, Adobe Acrobat Re...",[Plan and prepare advertising and promotional ...,"[Manage sales team, including setting goals, p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,55-3014.00,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des...",[],[],[],[],[],[Advanced TOMAHAWK Weapon Control System (ATWC...,[],[],[],[]
1012,55-3015.00,Command and Control Center Specialists,"Operate and monitor communications, detection,...",[],[],[],[],[],"[ACDS Block 1 Operator, AEGIS Console Operator...",[],[],[],[]
1013,55-3016.00,Infantry,Operate weapons and equipment in ground combat...,[],[],[],[],[],"[Combat Rifle Crewmember, Expeditionary Force ...",[],[],[],[]
1014,55-3018.00,Special Forces,"Implement unconventional operations by air, la...",[],[],[],[],[],"[Advance Seal Delivery System Maintainer, Amph...",[],[],[],[]
1015,55-3019.00,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...,[],[],[],[],[],[Advanced Foreign Counterintelligence Speciali...,[],[],[],[]

In [25]:
onet_overview = onet[["occupational_code", "job_description", "alternate_titles", "tools_used", "technical_skills", "core_tasks"]]
onet_overview.to_csv("onet_overview.csv", index=False)

In [13]:
skills = onet[["occupational_code", "skills"]]
skills.head()

  occupational_code                                             skills
0        11-1011.00  [{'Soft Skills': 'Reading Comprehension', 'Imp...
1        11-1011.03  [{'Soft Skills': 'Writing', 'Importance': 4.12...
2        11-1021.00                                                 []
3        11-1031.00                                                 []
4        11-2011.00  [{'Soft Skills': 'Active Listening', 'Importan...

In [17]:
skills_expanded = skills.explode("skills")
skills_expanded = skills_expanded.reset_index()
skills_expanded

,index,occupational_code,skills
0,0,11-1011.00,"{'Soft Skills': 'Reading Comprehension', 'Impo..."
1,0,11-1011.00,"{'Soft Skills': 'Writing', 'Importance': 4.12}"
2,0,11-1011.00,"{'Soft Skills': 'Speaking', 'Importance': 4.25}"
3,0,11-1011.00,"{'Soft Skills': 'Critical Thinking', 'Importan..."
4,0,11-1011.00,"{'Soft Skills': 'Social Perceptiveness', 'Impo..."
...,...,...,...
1384,1011,55-3014.00,NaN
1385,1012,55-3015.00,NaN
1386,1013,55-3016.00,NaN
1387,1014,55-3018.00,NaN
1388,1015,55-3019.00,NaN

In [24]:
skill = []
importance = []

for i in range(len(skills_expanded["skills"])):
    skill_data = skills_expanded["skills"][i]
    if isinstance(skill_data, dict):  # Check if the element is a dictionary
        skill.append(skill_data.get("Soft Skills", None))  # Use .get() to avoid KeyError
        importance.append(skill_data.get("Importance", None))
    else:
        skill.append(None)  # Append None if the element is not a dictionary
        importance.append(None)
skills_df = pd.DataFrame(
    {"occupational_code": skills_expanded["occupational_code"], "skill": skill, "importance": importance})
skills_df

     occupational_code                  skill  importance
0           11-1011.00  Reading Comprehension        4.12
1           11-1011.00                Writing        4.12
2           11-1011.00               Speaking        4.25
3           11-1011.00      Critical Thinking        4.38
4           11-1011.00  Social Perceptiveness        4.12
...                ...                    ...         ...
1384        55-3014.00                   None         NaN
1385        55-3015.00                   None         NaN
1386        55-3016.00                   None         NaN
1387        55-3018.00                   None         NaN
1388        55-3019.00                   None         NaN

[1389 rows x 3 columns]

In [26]:
skills_df.to_csv("onet_skills.csv", index=False)

In [29]:
# Split the occupational_code by '.' and filter rows where the last part is '00'
onet_filtered = onet[onet['occupational_code'].str.split('.').str[1] == '00']

onet_filtered["occupational_code"] = onet_filtered["occupational_code"].str.split('.').str[0]

# Reset the index of the filtered DataFrame
onet_filtered = onet_filtered.reset_index(drop=True)

onet_filtered

/var/folders/3b/1r88wmn97dldhp05hd1q9b200000gn/T/ipykernel_9622/1639701206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  onet_filtered["occupational_code"] = onet_filtered["occupational_code"].str.split('.').str[0]

,occupational_code,job_title,job_description,skills,education,work_experience,on_job_training,work_activities,alternate_titles,tools_used,technical_skills,core_tasks,supplemental_tasks
0,11-1011,Chief Executives,Determine and formulate policies and provide o...,"[{'Soft Skills': 'Reading Comprehension', 'Imp...",[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Aeronautics Commission Director, Agency Owner...","[Desktop calculator, Desktop computers, Notebo...","[Adobe Acrobat, AdSense Tracker, Atlassian JIR...",[Direct or coordinate an organization's financ...,"[Nominate citizens to boards or commissions., ..."
1,11-1021,General and Operations Managers,"Plan, direct, or coordinate the operations of ...",[],[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Area Manager, Business Coordinator, Business ...","[Desktop calculator, Mobile phones, Scanners, ...","[Act!, ActionWare, Adobe Acrobat, Adobe Creati...","[Review financial statements, sales or activit...",[Manage the movement of goods into and out of ...
2,11-1031,Legislators,"Develop, introduce, or enact laws and statutes...",[],[],[],[],[],"[Alderman, Assembly Member, Assembly Person, A...","[Laser printers, Notebook computers, Tablet co...","[Adobe Acrobat, Adobe FrameMaker, Antenna Hous...",[],[]
3,11-2011,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici...","[{'Soft Skills': 'Active Listening', 'Importan...",[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Account Director, Account Executive, Account ...","[Scanners, Desktop computers, Portable data in...","[Actuate BIRT, Adobe Acrobat, Adobe Acrobat Re...",[Plan and prepare advertising and promotional ...,"[Manage sales team, including setting goals, p..."
4,11-2021,Marketing Managers,"Plan, direct, or coordinate marketing policies...",[],[{'Education Level': 'Less than a High School ...,"[{'Work Experience Level': 'None', 'Importance...","[{'On Job Training': 'None', 'Importance Level...","[{'Work Activity': 'Getting Information', 'Imp...","[Account Supervisor, Brand Manager, Business D...","[Desktop computers, Laser fax machine, Noteboo...","[Adobe Acrobat, Adobe Acrobat Reader, Adobe Ac...","[Identify, develop, or evaluate marketing stra...",[Consult with buying personnel to gain advice ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,55-3014,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des...",[],[],[],[],[],[Advanced TOMAHAWK Weapon Control System (ATWC...,[],[],[],[]
863,55-3015,Command and Control Center Specialists,"Operate and monitor communications, detection,...",[],[],[],[],[],"[ACDS Block 1 Operator, AEGIS Console Operator...",[],[],[],[]
864,55-3016,Infantry,Operate weapons and equipment in ground combat...,[],[],[],[],[],"[Combat Rifle Crewmember, Expeditionary Force ...",[],[],[],[]
865,55-3018,Special Forces,"Implement unconventional operations by air, la...",[],[],[],[],[],"[Advance Seal Delivery System Maintainer, Amph...",[],[],[],[]
866,55-3019,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...,[],[],[],[],[],[Advanced Foreign Counterintelligence Speciali...,[],[],[],[]

In [30]:
onet_filtered.to_csv("onet_overview.csv", index=False)

In [31]:
skill = []
importance = []

skills = onet_filtered[["occupational_code", "skills"]]
skills_expanded = skills.explode("skills")
skills_expanded = skills_expanded.reset_index()

for i in range(len(skills_expanded["skills"])):
    skill_data = skills_expanded["skills"][i]
    if isinstance(skill_data, dict):  # Check if the element is a dictionary
        skill.append(skill_data.get("Soft Skills", None))  # Use .get() to avoid KeyError
        importance.append(skill_data.get("Importance", None))
    else:
        skill.append(None)  # Append None if the element is not a dictionary
        importance.append(None)
skills_df = pd.DataFrame(
    {"occupational_code": skills_expanded["occupational_code"], "skill": skill, "importance": importance})
skills_df

     occupational_code                  skill  importance
0              11-1011  Reading Comprehension        4.12
1              11-1011                Writing        4.12
2              11-1011               Speaking        4.25
3              11-1011      Critical Thinking        4.38
4              11-1011  Social Perceptiveness        4.12
...                ...                    ...         ...
1166           55-3014                   None         NaN
1167           55-3015                   None         NaN
1168           55-3016                   None         NaN
1169           55-3018                   None         NaN
1170           55-3019                   None         NaN

[1171 rows x 3 columns]

In [36]:
education = []
importance = []

educations = onet_filtered[["occupational_code", "education"]]
education_expanded = educations.explode("education")
education_expanded = education_expanded.reset_index()

for i in range(len(education_expanded["education"])):
    education_data = education_expanded["education"][i]
    if isinstance(education_data, dict):  # Check if the element is a dictionary
        education.append(education_data.get("Education Level", None))  # Use .get() to avoid KeyError
        importance.append(education_data.get("Importance Level", None))
    else:
        education.append(None)  # Append None if the element is not a dictionary
        importance.append(None)
education_df = pd.DataFrame(
    {"occupational_code": education_expanded["occupational_code"], "education": education, "importance": importance})
education_df

,occupational_code,education,importance
0,11-1011,Less than a High School Diploma,0.00
1,11-1011,High School Diploma - or the equivalent (for e...,4.46
2,11-1011,Post-Secondary Certificate - awarded for train...,0.00
3,11-1011,Some College Courses,0.00
4,11-1011,Associate's Degree (or other 2-year degree),5.15
...,...,...,...
8760,55-3014,None,NaN
8761,55-3015,None,NaN
8762,55-3016,None,NaN
8763,55-3018,None,NaN
8764,55-3019,None,NaN

In [37]:
skills_df.to_csv("onet_skills.csv", index=False)
education_df.to_csv("onet_education.csv", index=False)